<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RankingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankingRepository extends EntityRepository
{
	public function getGameId ($gameId)
    {
		$query = $this->createQueryBuilder('p')
		    ->where('p.game = :id')
		    ->setParameter('id', $gameId);

        return $query;
    }
}
