<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UnderRankingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnderRankingRepository extends EntityRepository
{
	public function findByRanking ($data)
    {
    	var_dump($data);exit;
		$query = $this->createQueryBuilder('p')
		    ->where('p.ranking = :id')
		    ->setParameter('id', $data);

        return $query;
    }
}
